services:
  qdrant:
    container_name: qdrantdb
    image: qdrant/qdrant:v1.11.5  
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # GRPC
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - similar-image-networks

  postgresql:
    container_name: postgresdb
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678  
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - similar-image-networks

networks:
  similar-image-networks:
